### ISSUE TITLE
WebSharper doesn't work with Visual Studio Code

### ISSUE THREAD

**Issue by mjarosie** [dotnet-websharper/core#1103] opened 2020-06-04 20:33 UTC
I'm still not sure if that's WebSharper, VSCode or Ionide-fsharp extension issue that I'm dealing with, I'd appreciate if someone tried it out to see if my problem is reproducible.

I'm developing with VSCode (most examples from https://github.com/websharper-samples recommend it, so maybe it's some kind of a regression error). When I open any code that uses WebSharper - VSCode features are reduced. For example, no errors are highlighted, unused imports are not detected, no tooltips appear.

Steps to reproduce:
```
dotnet new websharper-web -lang f# -n ws-test
cd ws-test
dotnet restore
code .
```

(Moving) picture is worth thousand words:

![vscode-websharper](https://user-images.githubusercontent.com/9082353/83804534-33ad5180-a6a6-11ea-8b15-85d3bce1fff1.gif)

Compare it to say console app:

![vscode-console](https://user-images.githubusercontent.com/9082353/83804642-5c354b80-a6a6-11ea-9497-0aeee54448bc.gif)

or SAFE:

![vscode-SAFE](https://user-images.githubusercontent.com/9082353/83806735-e3d08980-a6a9-11ea-9c4c-36de266d65e5.gif)

Different projects work, which proves that it's not an issue with my VSCode setup, I've been trying to figure out what's the difference between these projects, but not even sure what to look at...

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.300/

Host (useful for support):
  Version: 3.1.4
  Commit:  0090613580

.NET Core SDKs installed:
  2.1.806 [/usr/share/dotnet/sdk]
  3.1.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

Visual Studio Code:
```
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

Ionide-fsharp extension version: `4.11.1`

I'm using WSL2 Ubuntu if that makes any difference.

**Comment by granicz** [comment] 2020-06-04 20:51
I wonder if the `Sdk` in the project file has to do with it: the WebSharper client-server app template uses `Sdk="Microsoft.NET.Sdk.Web"` - perhaps Ionide can't deal with it anymore?

**Comment by granicz** [comment] 2020-06-04 21:00
Regardless, this is annoying indeed. The Getting Started video on the WebSharper home page uses VSC (although with C#, but should also work and did work with F#/Ionide). @Krzysztof-Cieslak any idea about why the code service could be broken in a WS project inside Ionide? Are we missing something in the project file?

**Comment by Krzysztof-Cieslak** [comment] 2020-06-04 21:16
Hmm... it's something weird going on - it seems that project is loaded correctly as it's shown in Ionide solution explorer, and initial line lenses are displayed correctly. Also, it seems line lenses are getting updated - they lose exact type information after you removed a bunch of code.

@mjarosie can you try to reproduce it outside of WSL - we had reports of some issues when using Ionide with it.

**Comment by isaacabraham** [comment] 2020-06-04 22:18
I'm pretty sure that Sdk.Web isn't the issue, because that's what we use with all of our web projects these days.

**Comment by Krzysztof-Cieslak** [comment] 2020-06-04 22:31
If `SDK.Web` was an issue project wouldn't load at all. Here it seems everything is fine but errors are not populating. Which suggest some issue with file URIs, likely due to mishandling of WSL paths.

**Comment by granicz** [comment] 2020-06-05 00:18
I just tried on a fresh Windows box with latest VSC and Ionide, same issue there :( I am getting hover info, but no errors/warnings.

**Comment by Jand42** [comment] 2020-06-05 23:50
The problem does seem to be caused by `WebSharper.Fsharp.targets` whichs appends arguments to `OtherFlags` then redirects the F# compiler tool to be the WS one instead of regular `fsc.exe`. So then this causes a problem with FsAutoComplete, its backend project cracker+checker fails on the unexpected flags instead of ignoring them.

@Krzysztof-Cieslak  Do you know any way how these `<OtherFlags>...` setters could be made so that they do not apply for Ionide/FsAutoComplete but run when built? Thanks!

Options to resolve on the WebSharper architecture side:
1. Revert to WS build task being one running after standard CoreCompile instead of replacing it (as WebSharper for C# does). Some performance loss is possible as project is double-checked, although fsc.exe build is more efficient than FCS due to not needing to keep as much assembly contents information for observing.
2. Pass extra arguments to `wsfsc.exe` in some other way. My idea would be to use a `--resource:obj/wsconfig.json` that is generated with a build task before CoreCompile and contains all resolved WebSharper build configs (resolved from hand-written `wsconfig.json`, and project MSBuild properties). This is just an embedded resource file as far as FsAutoComplete cares, but `wsfsc.exe` can parse it instead.

**Comment by granicz** [comment] 2020-06-06 11:43
@Jand42 Can you paste in a full set of `OtherFlags` we are using?

**Comment by Krzysztof-Cieslak** [comment] 2020-06-06 22:27
It’s surprising that other features seems to be working in such case. Maybe you could set this additional other flag only if MsBuild is *not* in DesignTimeBuild?

**Comment by Jand42** [comment] 2020-06-07 10:09
@Krzysztof-Cieslak Thanks a lot for the suggestion, I am testing added DesignTimeBuild/BuildingProject checks.

**Comment by Jand42** [comment] 2020-06-07 21:17
@mjarosie @Krzysztof-Cieslak  Hi, this is now released with https://github.com/dotnet-websharper/core/releases/tag/4.6.4.404

**Closed** 2020-06-08 05:32 UTC
Labels: 4.6.4.404, help wanted

**Comment by granicz** [comment] 2023-08-03 11:47
(Tracking a similar issue... FYI, the original fix was mistagged - [here](https://github.com/dotnet-websharper/core/commit/ddec725ad7662a81f5fbd9815dd70ccb9159d082) is the commit.)
