### ISSUE TITLE
Sitelet.Infer doesn't match by order of declaration

### ISSUE THREAD

**Issue by ajuch** [dotnet-websharper/core#1050] opened 2019-03-12 14:04 UTC
The docs at https://developers.websharper.com/docs/v4.x/fs/sitelets say that "If several cases have the same EndPoint, then parsing tries them in the order in which they are declared until one of them matches:"

This is not what actually happens when I try this example:

```F#
namespace ws_router

open WebSharper
open WebSharper.Sitelets
open WebSharper.UI

type EndPoint =
    | [<EndPoint "/">] Home
    | [<EndPoint "/">] Args of string

module Site =

    [<Website>]
    let Main =
        Sitelet.Infer (fun _ endpoint ->
            match endpoint with
            | EndPoint.Home -> Content.Text "Home"
            | EndPoint.Args name -> Content.Text (sprintf "Got Args: %s" (match name with s when s = "" -> "none!" | x -> x))
        )
```

When I run that example and go to localhost:xxx it displays "Got Args: none!" instead of "Home". For ReST APIs it is important that that distinction works as described in the docs!

**Comment by ajuch** [comment] 2019-03-12 15:06
Using WebSharper 4.5.7.322 and .Net Core  2.2.2.

**Comment by Jand42** [comment] 2019-03-12 15:27
Duplicate of https://github.com/dotnet-websharper/core/issues/1035.

Sorry, this is indeed an unintended side effect of some optimization, I am fixing to work as documented, should have done it earlier.

**Comment by Jand42** [comment] 2019-03-13 14:41
@ajuch Thanks for the report!
Fix is now released in https://github.com/dotnet-websharper/core/releases/tag/4.5.10.332

**Closed by Jand42** 2019-03-13 14:41 UTC
Labels: 4.5.10.332, bug

**Comment by ajuch** [comment] 2019-03-14 07:39
@Jand42 Great, thank you!
