### ISSUE TITLE
error NU1108: Cycle detected

### ISSUE THREAD

**Issue by alejandrocabanillas** [dotnet-websharper/core#1052] opened 2019-03-29 09:27 UTC
A suggestion about the getting started section and a reference for others finding the same issue:
I have followed the getting started instructions of the project main page:

```
dotnet new -i WebSharper.Templates
dotnet new websharper-web
dotnet run
```

and I have received an error message containing `error NU1108: Cycle detected`.
It happens because the folder where I executed the commands was called 'websharper'.
It's a well known problem not specific to websharper but to nuget restoring [issue](https://github.com/NuGet/Home/issues/6754).

Maybe the instructions could be modified:

```
dotnet new -i WebSharper.Templates
dotnet new websharper-web -n websharpersample -o .
dotnet run
```

Just for the sake of completion, other names containing websharper can throw other problems:
websharper-sample: `websharper-sample/WebSharper.UI.Templates/Main.g.cs(20,29): error CS0116: A namespace cannot directly contain members such as fields or methods`

**Comment by Jand42** [comment] 2019-03-29 12:21
@alejandrocabanillas Thanks a lot for the suggestion! I have added project names, although left out the `-o .` I think it could be a bit confusing if people see the `-n` thinking it will create its own directory but it won't because of the `-o .` that is easy to miss when just copy-pasting the command.

Your last issue is actually caused by the WebSharper.UI next C# templating code generator, created a bug ticket there and fix will be included in next release: https://github.com/dotnet-websharper/ui/issues/209

**Closed** 2019-03-29 12:22 UTC

**Comment by Jand42** [comment] 2019-04-12 13:56
@alejandrocabanillas Hi, now the namespace naming issue is also fixed in latest WebSharper.UI release https://github.com/dotnet-websharper/ui/releases/tag/4.5.10.166
